### ISSUE TITLE
Issue 1: Users can see their car

### ISSUE THREAD

**Issue by lyn-kim** [lyn-kim/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Add a new div in the HTML file with id of "my-car"
- [x] Create a new CSS file to style your driving environment
- [x] Remove all unnecessary CSS styling
- [x] Fix all errors
