### ISSUE TITLE
Issue 2: Users can turn their car

### ISSUE THREAD

**Issue by lyn-kim** [lyn-kim/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [ ] Query the car and listen for 'keydown' events on the document
- [ ] Create a data model that includes which way the car is facing, (north, south, east, or west)
- [ ] Create CSS classes for the car that relate to each direction (N, S, E, W) 
- [ ] Test & fix errors
- [ ] Remove unnecessary CSS styling
